# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pete D's Blog
email: peted70@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://petexr.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: peted70
github_username:  peted70

# Build settings
markdown: kramdown
#theme: minima
#remote_theme: pages-themes/cayman@v0.2.0
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-include-cache 

comments:
  provider: disqus
  disqus: 
    shortname: petexr

search: true

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true

minimal_mistakes_skin: "dark" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

author:
  name  : "Pete D"
  avatar  : "assets/images/avatar.png"
  bio : "XR"
  location  : "London, UK"
  email: "peted70@hotmail.com"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://www.petexr.com"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url: "https://twitter.com/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url: "https://facebook.com/"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peted70"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/peterdaukintis/"

paginate: 8 # amount of posts to show
paginate_path: /page:num/

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:peted70@hotmail.com
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/peted70"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/peterdaukintis/"

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
